export const LIST_PRODUCT = "LIST_PRODUCT";
export const BUY_ITEM = "BUY_ITEM";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const CHANGE_NOTIFY = "CHANGE_NOTIFY";